name: Lint OpenAPI schema
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  lint_openapi_schema:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Call lint script
        shell: pwsh
        run: ./documentation/lint-openapi.ps1